### ISSUE TITLE
issues with gp2 volume type

### ISSUE THREAD

**Issue by sobedrinker42** [opscode-cookbooks/aws#100]
hello, i just downloaded the latest version (2.5.0)

I'm trying to create and attach a 1TB gp2 volume with 3000 provisioned IOPS and can't seem to get past the following error:

[2015-01-16T17:44:08-05:00] ERROR: aws_ebs_volume[data_ebs_volume] (cookbook::createEBSdatavolume line 25) had an error: RuntimeError: IOPS param without piops volume type.
[2015-01-16T17:44:08-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

here is output from chef.

Resource Declaration:
 In /var/chef/cache/cookbooks/cookbook/recipes/createEBSdatavolume.rb

 25: aws_ebs_volume "data_ebs_volume" do
 26:   provider "aws_ebs_volume"
 27:   #availability_zone "us-east-1a"
 28:   aws_access_key aws['access_key']
 29:   aws_secret_access_key aws['secret_key']
 30:   size ebs_size
 31:   piops piops
 32:   volume_type 'gp2'
 33:   device "#{device_id}"
 34:   action [ :create, :attach ]
 35: end
 36: 

Compiled Resource:
 Declared in /var/chef/cache/cookbooks/cookbook/recipes/createEBSdatavolume.rb:25:in `from_file'

aws_ebs_volume("data_ebs_volume") do
  provider Chef::Provider::AwsEbsVolume
  action [:create, :attach]
  retries 0
  retry_delay 2
  cookbook_name "wordstream-postgresql"
  recipe_name "createEBSdatavolume"
  aws_access_key "XXXXXXXXXXXXXXXXXXX"
  aws_secret_access_key "XXXXXXXXXXXXXXXXXXXXXX"
  size 1024
  volume_type "gp2"
  device "/dev/sdc"
  piops 3000
  timeout 180
end

Is gp2 not a valid volume_type?  if it is valid, i'm I missing a key component?

thanks
Austin

**Comment by Scythril** [comment]
You're attempting to set a PIOPS value when not using the PIOPS volume type. The gp2 volume type has a baseline IOPS value based on the size of the disk you provision. Your 2 options would be:
* Remove the ```piops``` option if you really just want an SSD
* Change the ```volume_type``` to ```io1``` to use a provisioned IOPS volume

More info here: [Amazon EBS volume types](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)

**Comment by sobedrinker42** [comment]
yes, that was the issue.  thank you for the response!

**Comment by drywheat** [comment]
Shouldn't this issue be closed now?
