### ISSUE TITLE
Error "Aws::EC2::Errors::MissingParameter  The request must contain the parameter size/snapshot" related to #80

### ISSUE THREAD

**Issue by whysthatso** [opscode-cookbooks/aws#118]
Hey,
the error is produced by this cookbook code

    aws_ebs_raid "mysql_raid10_volume" do
        disk_count     4
        disk_size       250
        level               10
        filesystem      'ext4'
        disk_type       'standard'
    end

it gets compiled to:

    aws_ebs_volume("sdi1") do
      provider Chef::Provider::AwsEbsVolume
      action                    [:create, :attach]
      retries                    0
      retry_delay             2
      guard_interpreter  :default
      cookbook_name   "mysql"
      size                       250
      volume_type         "standard"
      piops                     0
      device                    "/dev/sdi1"
      timeout                 180
    end

If i run the compiled code in the same cookbook, the volume gets build and attached. However, the ebs_raid.rb provider seems to be the problem.

Has anybody seen this before, or can reproduce this?

Any advice on how to further troubleshoot the issue?

**Comment by whysthatso** [comment]
While checking the API call logs on AWS side via cloudtrail it indeed seems that the size value is not part of the call. Reverting back to v2.5.0, hence gem right_aws, the call is successful. However, then 
the issue "Can't create a RAID on an HVM instance #80" kicks in and the creation fails due to an incompatibility in the device naming scheme for HVM instances.

Could the gem be marked as incompatible of some sort? Also, are there any reasonable alternatives out there, any LRWP for creating EBS devices on HVM instances? I currently lack the resources time and knowledge to create something helpful, but maybe it is time to move forward for somebody to create an ebs cookbook?

**Comment by whysthatso** [comment]
just for completeness

Here is the call of the current cookbook version:

    "errorMessage": "The request must contain the parameter size/snapshot",
    "requestParameters": {
        "zone": "eu-west-1a",
        "volumeType": "standard"
    },
    "responseElements": null,

Here is one with the wrong device name (cookbook version 2.5.0):

    "requestParameters": {
        "volumeId": "vol-6xxxxx",
        "instanceId": "i-0xxxxx",
        "device": "/dev/sdi1",
        "deleteOnTermination": false
    },

    "responseElements": null,

And here is a successful api call (via aws website):

    "requestParameters": {
        "size": "250",
        "zone": "eu-west-1a",
        "volumeType": "gp2",
        "encrypted": false
    }

    "responseElements": {
        "volumeId": "vol-dxxxxx",
        "size": "250",
        "zone": "eu-west-1a",
        "status": "creating",
        "createTime": 1426667251303,
        "volumeType": "gp2",
        "iops": 750,
        "encrypted": false
    }

HTH

**Comment by DrMerlin** [comment]
I am getting this issue post 2.5 as well.  I needed to move to 2.7 for the Encryption options, but now I can't create any EBS Raids.

**Comment by DrMerlin** [comment]
I figured out what the problem is...
provider/ebs_raid.rb :349
-      snapshot_id creating_from_snapshot ? snapshots[i - 1] : ''
+      snapshot_id creating_from_snapshot ? snapshots[i - 1] : nil

I guess AWS SDK doesn't like '' as an empty snapshot_id.  nil seems to be working fine in my fork.

**Comment by DrMerlin** [comment]
https://github.com/opscode-cookbooks/aws/compare/master...needle-cookbooks:EbsRaid?expand=1

This also has some stuff in it for Encryption for Raids, which is missing from 2.7.0.

**Comment by liquid-sky** [comment]
Can confirm that changing to `nil` as per @DrMerlin fixes this.
