### ISSUE TITLE
EBS_Raid failing in 2.7.0 - see issue #118 AND Raid doesn't support Encryption

### ISSUE THREAD

**Issue by DrMerlin** [opscode-cookbooks/aws#129]
https://github.com/opscode-cookbooks/aws/issues/118

EBS Raid creation is failing with:
Error "Aws::EC2::Errors::MissingParameter The request must contain the parameter size/snapshot"

This is due to:
provider/ebs_raid.rb :349
snapshot_id creating_from_snapshot ? snapshots[i - 1] : ''

I guess AWS SDK doesn't like '' as an empty snapshot_id. I changed the line to: 
snapshot_id creating_from_snapshot ? snapshots[i - 1] : nil
nil is working fine in my fork.

Also,
EBS Volume was updated last week to support Encrypted volumes, but EBS Raid lacks the passthrough to allow creation of Encrypted volumes when creating them as part of a Raid.

**Comment by DrMerlin** [comment]
https://github.com/opscode-cookbooks/aws/pull/130

**Comment by DrMerlin** [comment]
Needs review

**Comment by Jan-Andre** [comment]
snapshots [nil]  works around the error.

**Comment by DrMerlin** [comment]
Since #156 was merged in lieu of this #130, I have opened Issue #164 and PR #165 with the remaining content.
