### ISSUE TITLE
elastic_lb LWRP does not remove nodes and always adds nodes to ELB

### ISSUE THREAD

**Issue by purgatorio** [opscode-cookbooks/aws#132]
The elastic_lb LWRP runs a check to see if the node is currently in the ELB, this check does not currently work.

Lines:
providers/elastic_lb:6
providers/elastic_lb:18
providers/elastic_lb:20

Current Behavior:
When actions de/register run, the checks listed above in lines 6 and 18 always fail. So it will always try to add the node to the ELB with register and will never remove a node with deregister.  converge_by will always claim that the action ran successfully. 

The deregister_instances_with_load_balancer method does not exist either. The correct method is deregister_instances_from_load_balancer

http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancing/Client.html#deregister_instances_from_load_balancer-instance_method

So if the deregister action were to run, it would fail when trying to run this method on line 20.

**Comment by miketheman** [comment]
Fixed in #133 - thanks!
